### ISSUE TITLE
Protocol relative URL-s are not composed correctly.

### ISSUE THREAD

**Issue by szepeviktor** [castor-labs/uri#3]
```php
echo Castor\Net\Uri::parse('//example.com/protocol-relative-url'), PHP_EOL;
```

produces `://example.com/protocol-relative-url`

**Comment by mnavarrocarter** [comment]
Thanks for highlighting the issue.

According to RFC 3986 Uris must have a scheme. A `InvalidUri` exception will be thrown in this case.

**Comment by szepeviktor** [comment]
Thank you.
